on:
  workflow_dispatch:
 
jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
 
    steps:
      # Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: show cloned repo
        run: |
          pwd

 
      # SonarCloud scan (ALL properties inline)
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} #autoâ€‘provided by GitHub
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=sonarqube-quality-check
            -Dsonar.projectKey=SonarQube-Quality-check_sonarqube
            -Dsonar.projectName=sonarqube
            -Dsonar.sources=.
            -Dsonar.exclusions=**/tests/**,**/docs/**,**/vendor/**,**/*.md
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.qualitygate.wait=true
            -Dsonar.qualitygate.timeout=300
     #   continue-on-error: true
 
      # Fetch Quality Gate status vuln report from SonarCloud API
      - name: Fetch Quality Gate Status
        run: |
          curl -s -u ${{ secrets.SONAR_TOKEN }}: \
            "https://sonarcloud.io/api/issues/search?componentKeys=SonarQube-Quality-check_sonarqube&ps=500" \
            | jq '.' >  sonarcloud-quality-gate.json
          cat sonarcloud-quality-gate.json || true
 
      # Upload the summary file as artifact
      - name: Upload SonarCloud Analysis with Quality Gate
        uses: actions/upload-artifact@v4
        with:
          name: SonarCloud Analysis with Quality Gate
          path: sonarcloud-quality-gate.json
